language: python
env:
  matrix:
    - PYVER=34
    - PYVER=35
    - PYVER=current
matrix:
  allow_failures:
    - env: PYVER=34
services:
  - docker
before_install:
  - docker pull base/archlinux
script:
  - docker build . -f Dockerfile_$PYVER
