language: python
env:
  matrix:
    - PYVER=python34_deprecated
    - PYVER=python35_ubuntu_1604
    - PYVER=current_arch
services:
  - docker
before_install:
  - docker pull base/archlinux
script:
  - docker build . -f Dockerfile_$PYVER
